version: '3.8'

services:
  # Backend Laravel
  backend:
    build:
      context: ./E2T1_Ileapaindegi_Backend
      dockerfile: docker/production/Dockerfile
    container_name: prod_laravel
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:POOuzPdCWvcIL7g2/yKi8oUKkDxpTng42cUm7yelcPc=
      DB_CONNECTION: mysql
      DB_HOST: e2t1-prod-db.cw8ix8v2vqgu.us-east-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_DATABASE: production_db
      DB_USERNAME: admin
      DB_PASSWORD: ikasle123
    networks:
      - app_network
    ports:
      - "8000:8000"

  # Frontend Vue
  frontend:
    build:
      context: ./E2T1_Ileapandegi_Frontend
      dockerfile: docker/production/Dockerfile
    container_name: prod_vue
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://100.25.200.198:8000/api
    depends_on:
      - backend
    networks:
      - app_network
    ports:
      - "80:80"
      - "443:443"

networks:
  app_network:
    driver: bridge